### ISSUE TITLE
vivid include all variables in the data, even thought I did not list them in the model

### ISSUE THREAD

**Issue by jielab** [AlanInglis/vividPackage#8]
Hi, there:

Please see the screenshot below. Although I only listed 6 covariates in my randomForest() model, vivi() output all variables. Those unlisted variables show up as 0.00. I hope that vivid did not actually do anything with those variables.

![image](https://github.com/AlanInglis/vivid/assets/26947455/ee4a9c14-67fb-4eff-96f6-b24555ac552b)

Best regards,
Jie

**Comment by AlanInglis** [comment]
Hi, 

Since all the variables are included in the data argument that is passed to `vivid` (despite only a selection of them being used in the model), `vivid` deals with these variables by just ignoring them and setting the values to zero. I suggest that you read either the vignette found at: https://alaninglis.github.io/vivid/articles/vividVignette.html

Or either paper related to the package, found at: 

1) https://www.tandfonline.com/doi/pdf/10.1080/10618600.2021.2007935
2) https://journal.r-project.org/articles/RJ-2023-054/RJ-2023-054.pdf

All of your related issues can be solved and explained by reading these articles. 

Marking this as closed as the issue has been solved.
